fix: golangci-lintを別workflowに
Misoten-B/airship-backend pull request #9
Opened 2023-10-26 09:11 UTC by mitsuYashi

## 関連isuue
close #8 

## 説明
- golangci-lintのActionsでのerror回避

## 変更の種類

- [ ] バグ修正（問題を修正する非互換の変更）
- [ ] 新機能（機能を追加する非互換の変更）
- [ ] 互換性のない変更（既存の機能が期待どおりに動作しなくなる修正または機能）

## チェックリスト:

- [ ] 自己レビュー
- [ ] 特に理解しにくい部分にコメントを追加
- [ ] 変更によって新しい警告が発生しない

## その他
- サンプルコードを持ってきただけなので、必要に応じて変更をかけてください。

2023-10-26 09:59 UTC, nakamura0907 commented
別ワークフローファイルを作成していますが、異なるジョブにすることではエラーは解消できないのでしょうか

2023-10-26 10:05 UTC, mitsuYashi commented
> 別ワークフローファイルを作成していますが、異なるジョブにすることではエラーは解消できないのでしょうか

指摘のあったように対応しました。

2023-10-26 10:20 UTC, nakamura0907 requested changes

2023-10-26 10:20 UTC, nakamura0907 commented on .github/workflows/go.yml
> +          go-version: '1.21'
buildジョブとバージョンが異なりますが合わせた方がいいかもしれないです。

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-single-dimension-matrix
のようにmatrixを使うのもありかも。または変数があればそちらで

2023-10-27 15:09 UTC, mitsuYashi commented on .github/workflows/go.yml
> +          go-version: '1.21'
今のところ二か所だけなのでハードコーディングで行きます。
matrixについてはoutputしないとjobsをまたいで使用できないようなので、実装コストがほんの少しだけ高そう。
また、よっぽどバージョンの変更はしないと思うので。

2023-10-30 01:21 UTC, nakamura0907 approved these changes

2023-10-30 01:22 UTC, merged